version: '3'
# Este es un bueno ejemplo de, a partir de dos imagenes distintas creo un contenedor en conjunto.
# La ventaja en este caso es que no tengo dolores de cabeza para, por ejemplo, setear mlflow.
services:
  jupyterlab:
    image: jupyter_docker       # Use the tagged image
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data        # Maps local 'data' folder to '/app/data' in the container
      - ./src:/app/src          # Maps local 'src' folder to '/app/src' in the container
      - ./notebooks:/app/notebooks  # Maps local 'notebooks' folder to '/app/notebooks' in the container
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.0.1  # Use the official MLflow image
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    volumes:
      - ./mlruns:/mlruns  # Persist MLflow runs
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns --host 0.0.0.0
